export const LOADING = 'LOADING';
export const MACHINES_DATA = 'MACHINES_DATA';
export const GET_MACHINE_BY_ID = 'GET_MACHINE_BY_ID';
export const UPDATE_MACHINE_NAME_BY_ID = 'UPDATE_MACHINE_NAME_BY_ID';
